[package]
name = "MathLang_DSN"
identifier = "mathlang_dsn"
version = "0.1.0"

[project]
name = "MathLang_DSN"
version = "0.1.0"
reason_version = "0.5.6.2"

[source]
entry = "src/main.rsn"

[compiler]
language_core = "0.7"
platform = "0.2"

[runtime]
backend = "RuntimeReal"
max_call_depth = 100
